using System.Collections.ObjectModel;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Threading;
using Wrapp.Models;
using Wrapp.Services;

namespace Wrapp.ViewModels;

/// <summary>
/// Phase-event consumption + per-package progress accounting for
/// <see cref="RunViewModel"/>. Owns the <c>OnPhaseChanged</c> dispatcher
/// (Invoke-WrappIntune / Invoke-WrappSccm phase events &#x2192; UI updates)
/// and its helpers: package lookup, progress recalculation, log colour
/// classification, and job-tracker push. Moved into a partial file so
/// the core VM focuses on command + connection state, and this file
/// owns "what to show as the run progresses."
/// </summary>
public partial class RunViewModel
{
    // -----------------------------------------------------------------------
    // Phase detection handler
    // -----------------------------------------------------------------------

    /// <summary>
    /// Regex phases the module now reports as typed <c>Write-WrappStep</c> events.
    /// While <see cref="_stepEventsOwnProgress"/> is set (the Intune path), these
    /// are driven by <see cref="ApplyStepEvent"/> instead and the regex path is
    /// suppressed to keep a single source of truth per step. Only
    /// <see cref="PhaseId.UploadProgress"/> stays regex-driven: it comes from the
    /// PS progress stream's structured PercentComplete (the [PROG:nn] prefix is
    /// generated by PowerShellService, not scraped prose). The SCCM path leaves
    /// the flag clear, so it keeps using these regexes until its module emits
    /// step events.
    /// </summary>
    private static readonly HashSet<PhaseId> StepEventOwnedPhases = new()
    {
        PhaseId.CollisionCheckStarted, PhaseId.CollisionDetected, PhaseId.CollisionCheckPassed,
        PhaseId.WrappingStarted, PhaseId.WrappingCopying, PhaseId.WrappingCopied,
        PhaseId.WrappingEncoding, PhaseId.WrappingCompleted,
        PhaseId.AppProcessingStarted, PhaseId.AppCreatingStarted, PhaseId.AppCreated,
        PhaseId.UploadMetadata, PhaseId.UploadConstructing, PhaseId.UploadRegistering,
        PhaseId.UploadGraphCreated, PhaseId.UploadContentVersion, PhaseId.UploadFileEntry,
        PhaseId.UploadStorageUriWaiting, PhaseId.UploadStarted,
        PhaseId.UploadCommitting, PhaseId.UploadCommitPolling,
        PhaseId.UploadCommitVersionUpdate, PhaseId.UploadCompleted,
        PhaseId.DependenciesStarted, PhaseId.SupersedenceStarted,
        PhaseId.AssignmentWaiting, PhaseId.AssignmentReady,
        PhaseId.AssignmentCompleted, PhaseId.AssignmentFailed,
        PhaseId.OrchestratorCompleted, PhaseId.Fatal, PhaseId.AppFailed,
    };

    private void OnPhaseChanged(PhaseEvent evt)
    {
        // When the module drives progress via typed step events (Intune),
        // ignore the equivalent regex phases so a single source owns each
        // step. Fine-grained upload / wrapping sub-steps are not gated.
        if (_stepEventsOwnProgress && StepEventOwnedPhases.Contains(evt.Phase))
            return;

        System.Windows.Application.Current.Dispatcher.Invoke(() =>
        {
            switch (evt.Phase)
            {
                case PhaseId.CollisionCheckStarted:
                    SetGlobalStep("Collision Check", StepState.Running);
                    break;

                case PhaseId.CollisionDetected:
                {
                    var pkg = FindPackage(evt.PackageName);
                    if (pkg is not null)
                    {
                        pkg.Outcome = PackageOutcome.Failed;
                        pkg.CurrentStepName = "Collision";
                        pkg.FailureReason = "Already exists in Intune";
                        SetStep(pkg, "Collision Check", StepState.Failed);
                    }
                    break;
                }

                case PhaseId.CollisionCheckPassed:
                    // Mark non-collided packages IN THIS TENANT PASS as passed.
                    foreach (var p in PackageProgressItems)
                    {
                        if (!InCurrentPass(p)) continue;
                        if (p.Outcome != PackageOutcome.Failed)
                            SetStep(p, "Collision Check", StepState.Succeeded);
                    }
                    break;

                case PhaseId.WrappingStarted:
                    SetGlobalStep("Wrapping", StepState.Running);
                    SetGlobalSubStep("Wrapping", "Preparing...", 0);
                    break;

                case PhaseId.WrappingCopying:
                    SetGlobalSubStep("Wrapping", "Copying source files...", 20);
                    break;

                case PhaseId.WrappingCopied:
                    SetGlobalSubStep("Wrapping", "Source files staged", 50);
                    break;

                case PhaseId.WrappingEncoding:
                    SetGlobalSubStep("Wrapping", "Creating .intunewin...", 60);
                    break;

                case PhaseId.WrappingCompleted:
                    SetGlobalSubStep("Wrapping", "Package created", 100);
                    SetGlobalStep("Wrapping", StepState.Succeeded);
                    break;

                case PhaseId.AppProcessingStarted:
                {
                    var pkg = FindPackage(evt.PackageName);
                    if (pkg is not null)
                    {
                        _activePackageName = evt.PackageName;
                        pkg.Outcome = PackageOutcome.Running;
                        pkg.CurrentStepName = "Processing...";
                        pkg.DetailText = string.Empty;
                        pkg.FailureReason = string.Empty;
                        pkg.SubStepPercent = 0;
                        SetStep(pkg, "App Creation", StepState.Running);
                    }
                    break;
                }

                case PhaseId.AppCreatingStarted:
                {
                    var pkg = FindPackage(evt.PackageName);
                    if (pkg is not null)
                    {
                        _activePackageName = evt.PackageName;
                        pkg.Outcome = PackageOutcome.Running;
                        pkg.CurrentStepName = "Creating app...";
                        pkg.DetailText = string.Empty;
                        pkg.FailureReason = string.Empty;
                        pkg.SubStepPercent = 0;
                        SetStep(pkg, "App Creation", StepState.Running);
                    }
                    break;
                }

                // -- IntuneWin32App sub-steps (applied to active package) --
                case PhaseId.UploadMetadata:
                {
                    var pkg = FindActivePackage();
                    if (pkg is not null)
                    {
                        pkg.CurrentStepName = "Reading .intunewin metadata...";
                        pkg.SubStepPercent = 2;
                        RecalcProgress(pkg);
                    }
                    break;
                }

                case PhaseId.UploadConstructing:
                {
                    var pkg = FindActivePackage();
                    if (pkg is not null)
                    {
                        pkg.CurrentStepName = "Building app body...";
                        pkg.SubStepPercent = 5;
                        RecalcProgress(pkg);
                    }
                    break;
                }

                case PhaseId.UploadRegistering:
                {
                    var pkg = FindActivePackage();
                    if (pkg is not null)
                    {
                        pkg.CurrentStepName = "Registering app in Intune...";
                        pkg.SubStepPercent = 8;
                        RecalcProgress(pkg);
                    }
                    break;
                }

                case PhaseId.UploadGraphCreated:
                {
                    var pkg = FindActivePackage();
                    if (pkg is not null)
                    {
                        pkg.CurrentStepName = "App registered";
                        pkg.DetailText = evt.Detail ?? string.Empty;
                        pkg.SubStepPercent = 12;
                        RecalcProgress(pkg);
                    }
                    break;
                }

                case PhaseId.UploadContentVersion:
                {
                    var pkg = FindActivePackage();
                    if (pkg is not null)
                    {
                        pkg.CurrentStepName = "Content version created";
                        pkg.SubStepPercent = 15;
                        RecalcProgress(pkg);
                    }
                    break;
                }

                case PhaseId.UploadFileEntry:
                {
                    var pkg = FindActivePackage();
                    if (pkg is not null)
                    {
                        pkg.CurrentStepName = "Preparing file entry...";
                        pkg.SubStepPercent = 18;
                        RecalcProgress(pkg);
                    }
                    break;
                }

                case PhaseId.UploadStorageUriWaiting:
                {
                    var pkg = FindActivePackage();
                    if (pkg is not null)
                    {
                        pkg.CurrentStepName = "Waiting for storage URI...";
                        pkg.SubStepPercent = 22;
                        RecalcProgress(pkg);
                    }
                    break;
                }

                case PhaseId.UploadStarted:
                {
                    var pkg = FindActivePackage();
                    if (pkg is not null)
                    {
                        pkg.CurrentStepName = "Uploading 0%";
                        pkg.SubStepPercent = 25;
                        RecalcProgress(pkg);
                    }
                    break;
                }

                case PhaseId.UploadProgress:
                {
                    var pkg = FindActivePackage();
                    if (pkg is not null && int.TryParse(evt.Detail, out var pct))
                    {
                        pkg.CurrentStepName = $"Uploading {pct}%";
                        // Map upload 0-100% to sub-step 25-80%
                        pkg.SubStepPercent = 25 + (int)(pct * 0.55);
                        RecalcProgress(pkg);
                    }
                    break;
                }

                case PhaseId.UploadCommitting:
                {
                    var pkg = FindActivePackage();
                    if (pkg is not null)
                    {
                        pkg.CurrentStepName = "Committing to Intune...";
                        pkg.SubStepPercent = 82;
                        RecalcProgress(pkg);
                    }
                    break;
                }

                case PhaseId.UploadCommitPolling:
                {
                    var pkg = FindActivePackage();
                    if (pkg is not null)
                    {
                        var attempt = evt.Detail ?? "?";
                        pkg.CurrentStepName = $"Processing commit (attempt {attempt})...";
                        // Slowly advance from 82% to 95% during polling
                        if (int.TryParse(attempt, out var n))
                            pkg.SubStepPercent = Math.Min(95, 82 + n);
                        RecalcProgress(pkg);
                    }
                    break;
                }

                case PhaseId.UploadCommitVersionUpdate:
                {
                    var pkg = FindActivePackage();
                    if (pkg is not null)
                    {
                        pkg.CurrentStepName = "Finalizing app version...";
                        pkg.SubStepPercent = 97;
                        RecalcProgress(pkg);
                    }
                    break;
                }

                case PhaseId.UploadCompleted:
                {
                    var pkg = FindActivePackage();
                    if (pkg is not null)
                    {
                        pkg.CurrentStepName = "App creation complete";
                        pkg.SubStepPercent = 100;
                        RecalcProgress(pkg);
                    }
                    break;
                }

                case PhaseId.AppCreated:
                {
                    var pkg = FindPackage(evt.PackageName);
                    if (pkg is not null)
                    {
                        pkg.CurrentStepName = "App created";
                        pkg.DetailText = string.Empty;
                        pkg.SubStepPercent = 0;
                        SetStep(pkg, "App Creation", StepState.Succeeded);
                    }
                    break;
                }

                case PhaseId.SccmAppCreating:
                {
                    var pkg = FindPackage(evt.PackageName);
                    if (pkg is not null)
                    {
                        pkg.Outcome = PackageOutcome.Running;
                        pkg.CurrentStepName = "Creating SCCM app...";
                        SetStep(pkg, "App Creation", StepState.Running);
                    }
                    break;
                }

                case PhaseId.DependenciesStarted:
                {
                    var pkg = FindPackage(evt.PackageName);
                    if (pkg is not null)
                    {
                        pkg.CurrentStepName = "Dependencies...";
                        SetStep(pkg, "Dependencies", StepState.Running);
                    }
                    break;
                }

                case PhaseId.SupersedenceStarted:
                {
                    var pkg = FindPackage(evt.PackageName);
                    if (pkg is not null)
                        pkg.CurrentStepName = "Supersedence...";
                    break;
                }

                case PhaseId.AssignmentWaiting:
                {
                    var pkg = FindPackage(evt.PackageName);
                    if (pkg is not null)
                    {
                        pkg.CurrentStepName = "Waiting for availability...";
                        SetStep(pkg, "Assignment", StepState.Running);
                    }
                    break;
                }

                case PhaseId.AssignmentReady:
                {
                    var pkg = FindPackage(evt.PackageName);
                    if (pkg is not null)
                    {
                        pkg.CurrentStepName = "Assigning...";
                    }
                    break;
                }

                case PhaseId.AssignmentCompleted:
                {
                    var pkg = FindPackage(evt.PackageName);
                    if (pkg is not null)
                    {
                        var detail = evt.Detail ?? "";
                        bool hasFailed = detail.Contains(", 0 failed") ? false : detail.Contains("failed");
                        if (hasFailed)
                        {
                            pkg.CurrentStepName = $"Assignments: {detail}";
                            pkg.DetailText = detail;
                            SetStep(pkg, "Assignment", StepState.Failed);
                        }
                        else
                        {
                            pkg.CurrentStepName = $"Assignments: {detail}";
                            SetStep(pkg, "Assignment", StepState.Succeeded);
                        }
                    }
                    break;
                }

                case PhaseId.AssignmentFailed:
                {
                    var pkg = FindPackage(evt.PackageName);
                    if (pkg is not null)
                    {
                        pkg.CurrentStepName = "Assignment failed";
                        SetStep(pkg, "Assignment", StepState.Failed);
                    }
                    break;
                }

                case PhaseId.SccmDeploymentsStarted:
                    SetGlobalStep("Content Distribution", StepState.Running, "SCCM");
                    break;

                case PhaseId.AppFailed:
                {
                    var pkg = FindPackage(evt.PackageName);
                    if (pkg is not null)
                    {
                        pkg.Outcome = PackageOutcome.Failed;
                        pkg.FailureReason = evt.Detail ?? "Unknown error";
                        pkg.CurrentStepName = "Failed";
                    }
                    break;
                }

                case PhaseId.OrchestratorCompleted:
                    FinalizeAllPackages();
                    break;

                case PhaseId.Fatal:
                    // Scope to the current tenant pass: a fatal DURING a tenant's
                    // run (e.g. "All packages have name collisions" for that
                    // tenant) must not fail packages that belong to other tenants
                    // and haven't run yet. Before any pass (auth/preflight fatal),
                    // _currentPassPackages is empty, so InCurrentPass is true for
                    // all and the fatal correctly fails the whole run.
                    foreach (var p in PackageProgressItems
                        .Where(p => (p.Outcome is PackageOutcome.Running or PackageOutcome.Pending)
                                    && InCurrentPass(p)))
                    {
                        p.Outcome = PackageOutcome.Failed;
                        p.FailureReason = evt.Detail ?? "Fatal error";
                        p.CurrentStepName = "Failed";
                    }
                    break;
            }
        });
    }

    // -----------------------------------------------------------------------
    // Phase detection helpers
    // -----------------------------------------------------------------------

    private PackageProgress? FindPackage(string? name)
    {
        if (string.IsNullOrEmpty(name)) return null;
        return PackageProgressItems.FirstOrDefault(
            p => string.Equals(p.PackageName, name.Trim(), StringComparison.OrdinalIgnoreCase));
    }

    private PackageProgress? FindActivePackage()
    {
        return FindPackage(_activePackageName);
    }

    /// <summary>
    /// Recalculates progress with sub-step interpolation.
    /// Sub-step percent (0-100) is mapped into the current step's fraction.
    /// </summary>
    private void RecalcProgress(PackageProgress pkg)
    {
        if (pkg.TotalSteps <= 0) return;
        double stepFraction = 100.0 / pkg.TotalSteps;
        pkg.ProgressPercent = pkg.CompletedSteps * stepFraction
            + (pkg.SubStepPercent / 100.0) * stepFraction;
        PushProgressToJobTracker();
    }

    /// <summary>Aggregates progress across all running packages and updates the job tracker.</summary>
    private void PushProgressToJobTracker()
    {
        if (!_currentRunJob.IsActive) return;
        var running = PackageProgressItems.Where(p => p.Outcome == PackageOutcome.Running).ToList();
        if (running.Count == 0) return;
        _currentRunJob.SetProgress((int)running.Average(p => p.ProgressPercent));
        var current = running.FirstOrDefault(p => !string.IsNullOrEmpty(p.CurrentStepName));
        if (current is not null)
            _currentRunJob.SetStatus($"Packaging: {current.CurrentStepName}");
    }

    private void SetGlobalSubStep(string stepName, string statusText, int subPercent)
    {
        foreach (var pkg in PackageProgressItems)
        {
            if (!InCurrentPass(pkg)) continue;
            if (pkg.Outcome is PackageOutcome.Skipped or PackageOutcome.Failed) continue;
            pkg.CurrentStepName = statusText;
            pkg.SubStepPercent = subPercent;
            RecalcProgress(pkg);
        }
    }

    /// <summary>
    /// True when <paramref name="pkg"/> belongs to the current per-tenant/site
    /// PackageAsync pass (or when no pass scoping is set). Keeps one tenant's
    /// "global" steps + finalization from touching another tenant's packages.
    /// </summary>
    private bool InCurrentPass(PackageProgress pkg)
        => _currentPassPackages.Count == 0 || _currentPassPackages.Contains(pkg.PackageName);

    private void SetGlobalStep(string stepName, StepState state, string? targetFilter = null)
    {
        foreach (var pkg in PackageProgressItems)
        {
            if (!InCurrentPass(pkg))
                continue;

            if (targetFilter is not null &&
                !pkg.Target.StartsWith(targetFilter, StringComparison.OrdinalIgnoreCase))
                continue;

            SetStep(pkg, stepName, state);
        }
    }

    private void SetStep(PackageProgress pkg, string stepName, StepState state)
    {
        var step = pkg.Steps.FirstOrDefault(
            s => string.Equals(s.Name, stepName, StringComparison.OrdinalIgnoreCase));
        if (step is null) return;

        step.State = state;

        if (state == StepState.Running)
            pkg.CurrentStepName = stepName;

        pkg.CompletedSteps = pkg.Steps.Count(s => s.State is StepState.Succeeded or StepState.Skipped);
        pkg.ProgressPercent = pkg.TotalSteps > 0
            ? (double)pkg.CompletedSteps / pkg.TotalSteps * 100.0
            : 0.0;
    }

    private void FinalizeAllPackages()
    {
        foreach (var pkg in PackageProgressItems)
        {
            // Only finalize packages processed in the current tenant/site pass.
            // A multi-tenant run fires OrchestratorCompleted once per tenant; without
            // this scope the first tenant's completion would finalize packages that
            // belong to later tenants (which are still Pending) as "Succeeded".
            if (!InCurrentPass(pkg))
                continue;

            // Don't override packages already marked as Skipped, Failed, or Cancelled
            if (pkg.Outcome is PackageOutcome.Running or PackageOutcome.Pending)
            {
                bool hasFailedStep = pkg.Steps.Any(s => s.State == StepState.Failed);
                bool hasSucceededStep = pkg.Steps.Any(s => s.State == StepState.Succeeded);
                if (hasFailedStep && hasSucceededStep)
                {
                    pkg.Outcome = PackageOutcome.PartialSuccess;
                    var failedNames = string.Join(", ", pkg.Steps.Where(s => s.State == StepState.Failed).Select(s => s.Name));
                    pkg.CurrentStepName = "Partial";
                    pkg.FailureReason = $"Failed: {failedNames}";
                }
                else if (hasFailedStep)
                {
                    pkg.Outcome = PackageOutcome.Failed;
                    var failedNames = string.Join(", ", pkg.Steps.Where(s => s.State == StepState.Failed).Select(s => s.Name));
                    pkg.CurrentStepName = "Failed";
                    pkg.FailureReason = $"Failed: {failedNames}";
                }
                else
                {
                    pkg.Outcome = PackageOutcome.Succeeded;
                    pkg.CurrentStepName = "Complete";
                    // Clear any stale failure detail so a succeeded package's
                    // detail accurately reflects success (defence against any
                    // residual cross-tenant bleed).
                    pkg.FailureReason = string.Empty;
                    pkg.DetailText = string.Empty;
                }
                pkg.ProgressPercent = 100.0;
            }
        }
    }

    // -----------------------------------------------------------------------
    // MSAL token acquisition + injection
    // -----------------------------------------------------------------------

    private async Task AcquireAndInjectTokenAsync()
    {
        var tenants = _appInfoVm.FullConfig.IntuneTenants
            .Where(t => !string.IsNullOrWhiteSpace(t.Key) && Guid.TryParse(t.Key, out _))
            .ToList();

        if (tenants.Count == 0)
        {
            AddLog("[WARN] No Intune tenants configured. Skipping MSAL auth (PS-side auth will be used).", "Warning");
            AppLogger.Warn("[Run] No Intune tenants configured -- skipping MSAL auth");
            return;
        }

        var hwnd = WindowHelper.GetMainWindowHwnd();

        MsalTokenResult? lastInjected = null;

        foreach (var tenant in tenants)
        {
            var displayName = !string.IsNullOrWhiteSpace(tenant.Name) ? tenant.Name : tenant.Key;

            var conn = IntuneConnections.FirstOrDefault(c =>
                string.Equals(c.TenantId, tenant.Key, StringComparison.OrdinalIgnoreCase));
            if (conn is not null && !conn.IsEnabled)
            {
                conn.State = ConnectionState.Skipped;
                conn.StatusText = "Skipped";
                AddLog($"[AUTH] {displayName}: skipped (disabled for this run).", "Verbose");
                continue;
            }

            try
            {
                AddLog($"[AUTH] Acquiring token for {displayName}...", "Info");
                AppLogger.Info($"[Run] Acquiring MSAL token for tenant {displayName} ({tenant.Key})");

                await _authService.InitializeForTenantAsync(tenant, hwnd);

                var token = await _authService.AcquireTokenAsync();

                _tenantTokens[tenant.Key] = token;
                lastInjected = token;

                var matchedConn = IntuneConnections.FirstOrDefault(c =>
                    string.Equals(c.TenantId, tenant.Key, StringComparison.OrdinalIgnoreCase));
                if (matchedConn is not null)
                    ConnectionChecker.ApplyTokenStatus(matchedConn, token, graphReachable: true);

                var who = !string.IsNullOrEmpty(token.UserPrincipalName)
                    ? token.UserPrincipalName
                    : "app credentials";
                AddLog($"[AUTH] {displayName}: token acquired ({who}), expires {token.ExpiresOnUtc:HH:mm:ss} UTC", "Info");
                AppLogger.Info($"[Run] {displayName}: token acquired ({who}), expires {token.ExpiresOnUtc:HH:mm:ss} UTC");
            }
            catch (OperationCanceledException)
            {
                AddLog($"[AUTH] Authentication cancelled for {displayName}.", "Warning");
                AppLogger.Warn($"[Run] Authentication cancelled for tenant {displayName}");
                throw; // propagate to abort the run
            }
            catch (Exception ex)
            {
                AddLog($"[AUTH] {displayName}: MSAL authentication failed - {ex.Message}", "Error");
                AppLogger.Error($"[Run] {displayName}: MSAL authentication failed: {ex.Message}");
            }
        }

        // Record the last acquired token for the UI expiry countdown. No pool
        // injection: each tenant's PackageAsync injects its OWN token per pipeline
        // (InjectMsalApp) on the run's dedicated pool -- a pool-level inject here
        // only ever seeded the ambient pool (which the run doesn't use) with the
        // last tenant's token, so it was vestigial.
        if (lastInjected is not null)
        {
            _lastToken = lastInjected;
            StartTokenTimer();
        }
        else
        {
            AddLog("[AUTH] No tokens acquired. Falling back to PowerShell-side authentication.", "Warning");
            AppLogger.Warn("[Run] No MSAL tokens acquired for any tenant");
        }
    }

    // -----------------------------------------------------------------------
    // Step events + encryption key capture
    // -----------------------------------------------------------------------

    /// <summary>
    /// Drives per-package progress from the module's structured
    /// <c>Write-WrappStep</c> events. Because each event carries the exact
    /// package + tenant it applies to, progress no longer relies on regex
    /// log-scraping with global (bleed-prone) mutators for the Intune path. The
    /// module-owned regex phases are suppressed while <see cref="_stepEventsOwnProgress"/>
    /// is set (see <see cref="OnPhaseChanged"/>); the vendored IntuneWin32App
    /// upload sub-steps and the Wrapping sub-steps still drive fine-grained
    /// progress within a package's "App Creation" / "Wrapping" step.
    ///
    /// Runs on the PS output-stream thread, so all UI mutation is marshalled to
    /// the dispatcher, exactly like <see cref="OnPhaseChanged"/>.
    /// </summary>
    private void HandleStepEvent(System.Management.Automation.PSObject obj, string tenantId)
    {
        var evt = Models.StepEvent.FromPSObject(obj);
        if (evt is null) return;

        var target = string.IsNullOrEmpty(evt.TenantId) ? tenantId : evt.TenantId;
        AppLogger.Info($"[STEP] {target}: {evt.Package} / {evt.Step} / {evt.Kind}"
            + (string.IsNullOrEmpty(evt.Error) ? "" : $" -- {evt.Error}")
            + (string.IsNullOrEmpty(evt.Detail) ? "" : $" ({evt.Detail})"));

        System.Windows.Application.Current.Dispatcher.Invoke(() => ApplyStepEvent(evt));
    }

    /// <summary>Maps a module step id to its <see cref="PackageProgress"/> step name.</summary>
    private static string? MapStepName(string step) => step switch
    {
        "Collision"    => "Collision Check",
        "Wrapping"     => "Wrapping",
        "AppCreation"  => "App Creation",
        "Dependencies" => "Dependencies",
        "Assignment"   => "Assignment",
        _              => null,
    };

    private void ApplyStepEvent(Models.StepEvent evt)
    {
        // Broadcast signals ('*') act on the whole current tenant pass.
        switch (evt.Step)
        {
            case "TenantPass":
                // The module owns the tenant loop and reports each
                // pass boundary; Detail carries the pass's package names
                // ('|'-separated). This replaces the .NET loop iteration as the
                // source of the per-pass progress scope (_currentPassPackages).
                if (evt.Kind == "Start")
                {
                    _currentPassPackages.Clear();
                    foreach (var n in (evt.Detail ?? "").Split('|', StringSplitOptions.RemoveEmptyEntries))
                        _currentPassPackages.Add(n.Trim());
                    AddLog($"[PHASE] Tenant pass started: {evt.TenantId} ({_currentPassPackages.Count} package(s))", "Info");
                }
                // Success/Fail: nothing to mutate -- the pass's RunComplete
                // already finalized its packages; the set stays scoped until
                // the next pass starts so late events can't bleed.
                return;

            case "Fatal":
                foreach (var p in PackageProgressItems
                    .Where(p => (p.Outcome is PackageOutcome.Running or PackageOutcome.Pending)
                                && InCurrentPass(p)))
                {
                    p.Outcome = PackageOutcome.Failed;
                    p.FailureReason = string.IsNullOrEmpty(evt.Error) ? "Fatal error" : evt.Error!;
                    p.CurrentStepName = "Failed";
                }
                return;

            case "RunComplete":
                FinalizeAllPackages();
                return;
        }

        // Broadcast step events (Package = '*'): a step shared by every package
        // in the current tenant pass (Wrapping -- one .intunewin per pass).
        if (evt.Package == "*")
        {
            var broadcastStep = MapStepName(evt.Step);
            if (broadcastStep is null) return;
            switch (evt.Kind)
            {
                case "Start":
                    SetGlobalStep(broadcastStep, StepState.Running);
                    break;
                case "Progress":
                    SetGlobalSubStep(broadcastStep, evt.Detail ?? broadcastStep, evt.Percent ?? 0);
                    break;
                case "Success":
                    SetGlobalStep(broadcastStep, StepState.Succeeded);
                    break;
                case "Fail":
                    SetGlobalStep(broadcastStep, StepState.Failed);
                    break;
            }
            return;
        }

        var pkg = FindPackage(evt.Package);
        if (pkg is null) return;

        var stepName = MapStepName(evt.Step);
        if (stepName is null) return;

        switch (evt.Kind)
        {
            case "Start":
                if (evt.Step == "AppCreation")
                {
                    // The vendored upload sub-steps (OnPhaseChanged) apply to the
                    // active package; set it here since the regex that used to do
                    // so is suppressed while StepEvents own progress.
                    _activePackageName = pkg.PackageName;
                    pkg.Outcome = PackageOutcome.Running;
                    pkg.DetailText = string.Empty;
                    pkg.FailureReason = string.Empty;
                    pkg.SubStepPercent = 0;
                }
                SetStep(pkg, stepName, StepState.Running);
                break;

            case "Progress":
            {
                // Sub-step refinement within a Running step (the vendored
                // upload pipeline, translated module-side). Detail is
                // "status" or "status|extra" (e.g. the Graph app id).
                var parts = (evt.Detail ?? "").Split('|', 2);
                pkg.CurrentStepName = parts[0];
                if (parts.Length > 1) pkg.DetailText = parts[1];
                if (evt.Percent is int pct) pkg.SubStepPercent = pct;
                RecalcProgress(pkg);
                break;
            }

            case "Success":
                if (evt.Step == "AppCreation")
                {
                    pkg.SubStepPercent = 0;
                    pkg.DetailText = string.Empty;
                }
                SetStep(pkg, stepName, StepState.Succeeded);
                break;

            case "Skip":
                SetStep(pkg, stepName, StepState.Skipped);
                break;

            case "Fail":
                pkg.Outcome = PackageOutcome.Failed;
                if (!string.IsNullOrEmpty(evt.Error))
                    pkg.FailureReason = evt.Error!;
                pkg.CurrentStepName = stepName == "Collision Check" ? "Collision" : "Failed";
                SetStep(pkg, stepName, StepState.Failed);
                break;
        }
    }

    private void CaptureEncryptionKeys(System.Management.Automation.PSObject obj, string tenantId)
    {
        if (_keyStore is null) return;
        try
        {
            var type = obj.Properties["_Type"]?.Value?.ToString();
            if (type != "EncryptionKeys") return;

            var keys = new Models.EncryptionKeyInfo
            {
                AppId                  = obj.Properties["AppId"]?.Value?.ToString() ?? "",
                DisplayName            = obj.Properties["DisplayName"]?.Value?.ToString() ?? "",
                TenantId               = obj.Properties["TenantId"]?.Value?.ToString() ?? tenantId,
                EncryptionKey          = obj.Properties["EncryptionKey"]?.Value?.ToString() ?? "",
                InitializationVector   = obj.Properties["InitializationVector"]?.Value?.ToString() ?? "",
                MacKey                 = obj.Properties["MacKey"]?.Value?.ToString() ?? "",
                Mac                    = obj.Properties["Mac"]?.Value?.ToString() ?? "",
                ProfileIdentifier      = obj.Properties["ProfileIdentifier"]?.Value?.ToString() ?? "ProfileVersion1",
                FileDigest             = obj.Properties["FileDigest"]?.Value?.ToString() ?? "",
                FileDigestAlgorithm    = obj.Properties["FileDigestAlgorithm"]?.Value?.ToString() ?? "SHA256",
                PackageName            = obj.Properties["PackageName"]?.Value?.ToString() ?? "",
                SetupFile              = obj.Properties["SetupFile"]?.Value?.ToString() ?? "",
                InnerFileName          = obj.Properties["InnerFileName"]?.Value?.ToString() ?? "",
                UnencryptedContentSize = long.TryParse(obj.Properties["UnencryptedContentSize"]?.Value?.ToString(), out var sz) ? sz : 0,
                SavedAt                = SystemClock.UtcNow.ToString("o"),
                SavedBy                = Environment.UserName,
            };

            if (string.IsNullOrEmpty(keys.AppId) || string.IsNullOrEmpty(keys.EncryptionKey)) return;

            // Silent-skip when the vault gate is OFF. The capture
            // path is invisible UI (fires-and-forgets during packaging), so
            // there's no button to grey out -- the gate check itself is the
            // entire opt-out surface for this flow. The "KEYS LOST" dialog
            // path below stays as a defensive net for code paths that reach
            // SaveKeysAsync without going through this guard.
            if (_featureGate is not null
                && !_featureGate.IsEnabled(Models.WrappFeatures.AzureDevOpsKeyVault))
            {
                AppLogger.Info($"[Run] Encryption keys captured for '{keys.DisplayName}' "
                    + $"({keys.AppId}) but vault gate is OFF -- keys not pushed. "
                    + $"Reason: {_featureGate.DescribeWhyDisabled(Models.WrappFeatures.AzureDevOpsKeyVault)}");
                return;
            }

            // Fire-and-forget -- don't block the packaging run
            _ = Task.Run(async () =>
            {
                try
                {
                    await _keyStore.SaveKeysAsync(keys);
                    AddLog($"[INFO] Encryption keys saved for '{keys.DisplayName}' ({keys.AppId})", "Info");
                }
                catch (Services.EncryptionKeyStoreService.DevOpsVaultNotConfiguredException)
                {
                    // The DevOps vault is the only place keys live now.
                    // With no vault configured, the keys are gone --
                    // call that out loudly so the user knows to configure
                    // Settings -> Key Vault before the next packaging run.
                    var msg = $"Encryption keys captured for '{keys.DisplayName}' ({keys.AppId}) "
                            + "but the Azure DevOps key vault is not configured -- KEYS LOST. "
                            + "Configure Settings -> Key Vault and re-run packaging to produce a fresh keypair.";
                    AppLogger.Warn($"[Run] {msg}");
                    AddLog($"[WARN] {msg}", "Warning");
                    try
                    {
                        var dispatcher = System.Windows.Application.Current?.Dispatcher;
                        if (dispatcher is not null)
                        {
                            await dispatcher.InvokeAsync(async () =>
                                await FluentDialog.ShowInfoAsync(
                                    "Encryption keys discarded",
                                    "Packaging captured encryption keys but the Azure DevOps key vault "
                                    + "is not configured. The keys have been discarded. Configure the vault "
                                    + "in Settings -> Key Vault, then re-run the packaging to produce a "
                                    + "fresh keypair."));
                        }
                    }
                    // must-stay-silent: the dialog is a courtesy on top of the
                    // already-logged WARN; if the UI thread is gone (shutdown)
                    // or the dispatcher rejects the dispatch, the WARN is the
                    // documented user signal.
                    catch { }
                }
                catch (Exception ex)
                {
                    // Persist to app.log as well as the (transient) run pane, so
                    // a vault push/PR failure stays diagnosable after the run
                    // window closes. The message carries the app id; the vault
                    // layer (EncryptionKeyStoreService) logs the DevOps server
                    // response separately.
                    AppLogger.Warn($"[Run] Failed to save encryption keys for "
                        + $"'{keys.DisplayName}' ({keys.AppId}): {ex.Message}");
                    AddLog($"[WARN] Failed to save encryption keys: {ex.Message}", "Warning");
                }
            });
        }
        catch { /* swallow -- key capture must never break the run */ }
    }

    private void WarnPastDates()
    {
        var now = SystemClock.UtcNow;
        var config = _appInfoVm.FullConfig;

        if (Target is RunTarget.Intune or RunTarget.Both)
        {
            foreach (var pkg in config.Script.IntunePackager.Packages)
            {
                foreach (var a in pkg.Assignments)
                {
                    CheckDate(a.AvailableTime, "AvailableTime", pkg.AppName, a.DisplayName, now);
                    CheckDate(a.DeadlineTime, "DeadlineTime", pkg.AppName, a.DisplayName, now);
                }
            }
        }

        if (Target is RunTarget.SCCM or RunTarget.Both)
        {
            foreach (var pkg in config.Script.SCCMPackager.Packages)
            {
                foreach (var d in pkg.Deployments)
                {
                    CheckDate(d.AvailableDateTime, "AvailableDateTime", pkg.AppName, d.DisplayName, now);
                    CheckDate(d.DeadlineDateTime, "DeadlineDateTime", pkg.AppName, d.DisplayName, now);
                }
            }
        }
    }

    private void CheckDate(string? value, string fieldName, string package, string entry, DateTime now)
    {
        if (string.IsNullOrEmpty(value)) return;
        // Skip ASAP sentinel
        if (value.StartsWith("0001-01-01")) return;

        if (DateTime.TryParse(value, System.Globalization.CultureInfo.InvariantCulture,
            System.Globalization.DateTimeStyles.AdjustToUniversal, out var dt) && dt < now)
        {
            AddLog($"[WARN] {package} / {entry}: {fieldName} is in the past ({dt:yyyy-MM-dd HH:mm} UTC) - will be treated as ASAP.", "Warning");
        }
    }

    // -----------------------------------------------------------------------
    // Log helpers
    // -----------------------------------------------------------------------

    private void AddLog(string line, string color = "Default")
    {
        lock (_logLock)
        {
            LogLines.Add(new LogEntry { Content = line, ColorCode = color });
        }
    }

    private const string LogInitPrefix = "[INFO] Log initialized: ";

    private void AddLogFromRaw(string raw)
    {
        // Progress lines update the phase detector but are not shown in the log
        if (raw.StartsWith("[PROG:"))
        {
            _phaseDetector.ProcessLine(raw);
            return;
        }

        // Capture the actual log file path reported by the PS module
        if (raw.StartsWith(LogInitPrefix))
        {
            _actualLogFilePath = raw[LogInitPrefix.Length..].Trim();
            OnPropertyChanged(nameof(LogFilePath));
        }

        string color = raw.StartsWith("[ERROR]")    ? "Error"
                     : raw.StartsWith("[WARN]")     ? "Warning"
                     : raw.StartsWith("[INFO]")     ? "Info"
                     : raw.StartsWith("[VERB]")     ? "Verbose"
                     : raw.StartsWith("[CANCEL")    ? "Warning"
                     : "Default";
        AddLog(raw, color);
    }
}
