using System.IO;
using System.Text.Json;
using Wrapp.Models;

namespace Wrapp.Services;

/// <summary>
/// Owns <c>%LOCALAPPDATA%\Wrapp\user-defaults.json</c> — the SHARED,
/// secret-free projection of the user's package/assignment defaults and
/// endpoint script paths that BOTH the GUI and the Wrapp.Packager PowerShell
/// module read (CLI/UI parity).
///
/// <para>Flow: the GUI remains the editor — Settings → Preferences persists to
/// settings.json as before, and this service re-exports the defaults sections
/// to the sidecar on every preferences save (plus once at startup so a fresh
/// install is CLI-ready before Preferences is ever opened). The PS module
/// reads the sidecar per run via <c>Get-WrappUserDefaults</c> and layers it
/// over its own Defaults.psd1; the bundle's Config.json still wins.
/// Precedence everywhere: bundle config &gt; user defaults &gt; module/shipped
/// defaults.</para>
///
/// <para>Also the in-process source for the endpoint template tokens
/// (<c>{{TagFolder}}</c> / <c>{{LocalAppFolder}}</c>) used when writing bundle
/// scripts — see <see cref="TemplateService.ApplyTokens"/> and
/// <c>BundleService.ApplyTokens</c>.</para>
/// </summary>
public static class UserDefaultsService
{
    private static AppSettings? _settings;

    /// <summary>Sidecar path: sibling of settings.json (module reads %LOCALAPPDATA%\Wrapp\user-defaults.json).</summary>
    public static string SidecarPath =>
        Path.Combine(
            Path.GetDirectoryName(PlatformConfig.SettingsPath) ?? PlatformConfig.SettingsPath,
            "user-defaults.json");

    /// <summary>
    /// Binds the live <see cref="AppSettings"/> instance (call once at startup
    /// and after settings reloads). Token getters below read from it.
    /// </summary>
    public static void Init(AppSettings settings) => _settings = settings;

    /// <summary>Endpoint tag folder for {{TagFolder}} expansion (seed fallback when unset).</summary>
    public static string EndpointTagFolder =>
        string.IsNullOrWhiteSpace(_settings?.EndpointTagFolder)
            ? ModuleDefaultsSeed.EndpointTagFolder
            : _settings!.EndpointTagFolder;

    /// <summary>Endpoint local app root for {{LocalAppFolder}} expansion (seed fallback when unset).</summary>
    public static string EndpointLocalAppFolder =>
        string.IsNullOrWhiteSpace(_settings?.EndpointLocalAppFolder)
            ? ModuleDefaultsSeed.EndpointLocalAppFolder
            : _settings!.EndpointLocalAppFolder;

    /// <summary>
    /// Writes the sidecar from the current settings (atomic). Shape is a
    /// CONTRACT with the module's <c>Get-WrappUserDefaults</c>/
    /// <c>Merge-WrappUserDefaults</c> — property names must not drift.
    /// Never throws: a failed export logs and leaves the previous sidecar.
    /// </summary>
    public static Task ExportAsync(AppSettings settings, string? path = null)
        => Task.Run(() => Export(settings, path));

    /// <summary>
    /// Synchronous export -- exists so <see cref="SettingsService"/> can write
    /// settings.json and this sidecar under ONE <see cref="CrossProcessLock"/>
    /// hold (M2): the pair can't tear across concurrent Wrapp instances.
    /// </summary>
    public static void Export(AppSettings settings, string? path = null)
    {
        try
        {
            path ??= SidecarPath;
            var payload = new
            {
                _comment = "Generated by Wrapp (Settings > Preferences). Shared with the "
                         + "Wrapp.Packager PowerShell module for CLI/UI parity. Safe to edit "
                         + "by hand for CLI-only use; the GUI overwrites it on preferences save.",
                Endpoint = new
                {
                    TagFolder      = string.IsNullOrWhiteSpace(settings.EndpointTagFolder)
                                       ? ModuleDefaultsSeed.EndpointTagFolder : settings.EndpointTagFolder,
                    LocalAppFolder = string.IsNullOrWhiteSpace(settings.EndpointLocalAppFolder)
                                       ? ModuleDefaultsSeed.EndpointLocalAppFolder : settings.EndpointLocalAppFolder,
                },
                settings.IntunePackageDefaults,
                settings.IntuneMetadataDefaults,
                settings.IntuneAssignmentDefaults,
                settings.SccmPackageDefaults,
                settings.SccmMetadataDefaults,
                settings.SccmDeploymentDefaults,
            };
            var json = JsonSerializer.Serialize(payload, JsonDefaults.Pretty);
            // M2: same lock as SettingsService -- named mutexes are reentrant,
            // so the nested call from the preferences save is safe, and the
            // direct first-run export is serialized against other instances.
            CrossProcessLock.Run("Settings", () => AtomicFile.WriteAllText(path, json));
            AppLogger.Info($"User defaults exported: {path}");
        }
        catch (Exception ex)
        {
            AppLogger.Warn($"UserDefaultsService.Export failed: {ex.Message}");
        }
    }

    /// <summary>
    /// Startup hook: binds settings for token expansion and ensures the
    /// sidecar exists so CLI runs work before Preferences was ever opened.
    /// </summary>
    public static async Task InitializeAsync(AppSettings settings)
    {
        Init(settings);
        if (!File.Exists(SidecarPath))
            await ExportAsync(settings);
    }
}
